create table public."Porta" (
  "idPorta" integer generated always as identity not null,
  "nomePorta" character varying(100) not null,
  "statusPorta" smallint not null default 1,
  "abrirPorta" boolean not null default false,
  bloqueada boolean null default false,
  constraint Porta_pkey primary key ("idPorta")
) TABLESPACE pg_default;

create table public."PortaUsuario" (
  "idPortaUsuario" integer generated always as identity not null,
  "idPorta" integer not null,
  "idUsuario" uuid not null,
  status smallint null default '0'::smallint,
  constraint PortaUsuario_pkey primary key ("idPortaUsuario"),
  constraint PortaUsuario_idPorta_fkey foreign KEY ("idPorta") references "Porta" ("idPorta"),
  constraint PortaUsuario_idUsuario_fkey foreign KEY ("idUsuario") references auth.users (id)
) TABLESPACE pg_default;

create table public."Acesso" (
  "idAcesso" integer generated always as identity not null,
  "horarioAcesso" timestamp without time zone not null default CURRENT_TIMESTAMP,
  "statusAcesso" smallint not null default 1,
  "idUsuario" uuid not null,
  "idPorta" integer not null,
  "saidaAcesso" timestamp with time zone null,
  constraint Acesso_pkey primary key ("idAcesso"),
  constraint Acesso_idPorta_fkey foreign KEY ("idPorta") references "Porta" ("idPorta"),
  constraint fk_usuario_auth foreign KEY ("idUsuario") references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public."FluxoAcesso" (
  "idFluxoAcesso" bigint generated always as identity not null,
  "statusFluxoAcesso" smallint not null,
  horario timestamp with time zone not null default now(),
  "idAcesso" bigint not null,
  constraint FluxoAcesso_pkey primary key ("idFluxoAcesso"),
  constraint FK_FluxoAcesso_Acesso foreign KEY ("idAcesso") references "Acesso" ("idAcesso") on delete CASCADE,
  constraint FluxoAcesso_statusFluxoAcesso_check check (("statusFluxoAcesso" = any (array[0, 1])))
) TABLESPACE pg_default;

create index IF not exists "IDX_FluxoAcesso_idAcesso" on public."FluxoAcesso" using btree ("idAcesso") TABLESPACE pg_default;

create index IF not exists "IDX_FluxoAcesso_horario" on public."FluxoAcesso" using btree (horario) TABLESPACE pg_default;

create table public."TotalAcesso" (
  "idTotalAcesso" bigint generated always as identity not null,
  "qtdEntrada" integer not null default 0,
  "qtdSaida" integer not null default 0,
  "idAcesso" bigint not null,
  constraint TotalAcesso_pkey primary key ("idTotalAcesso"),
  constraint TotalAcesso_idAcesso_key unique ("idAcesso"),
  constraint FK_TotalAcesso_Acesso foreign KEY ("idAcesso") references "Acesso" ("idAcesso") on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists "IDX_TotalAcesso_idAcesso" on public."TotalAcesso" using btree ("idAcesso") TABLESPACE pg_default;

create table public.user_roles (
  id uuid not null,
  admin boolean null default false,
  constraint user_roles_pkey primary key (id),
  constraint user_roles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.log (
  "idUsuario" uuid not null,
  acao smallint not null,
  tabela character varying(100) not null,
  data timestamp without time zone null default CURRENT_TIMESTAMP,
  "idLog" bigint generated by default as identity not null,
  constraint log_pkey primary key ("idLog"),
  constraint log_idUsuario_fkey foreign KEY ("idUsuario") references auth.users (id)
) TABLESPACE pg_default;
